#!/usr/bin/python3 

import socket 
from art import *

tprint("SGS",font="block",chr_ignore=True)
print("---------  Cyber Python  ---------")
print("")

s = socket.socket()
host = socket.gethostname()
port = 5555

s.connect((host,port))
print(s.recv(200))
s.close()
# server  لتشغيل هذا البرنامج يجب عليك تشغيل البرنامج
